# Generated by Django 5.0.6 on 2024-07-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_address_center_about_center_location_center_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center_about',
            name='body',
        ),
    ]
