# Generated by Django 5.0.6 on 2024-07-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_center_about_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
    ]
